FROM python:3.11-slim
WORKDIR /app

RUN apt-get update
RUN apt-get install sqlite3 -y

# Installing dependencies
COPY ./requirements.txt /app/
RUN pip install -r requirements.txt

# Copying the entire backend to the container
COPY . ./

CMD [ "flask", "run", "--host=0.0.0.0"]